CREATE TABLE IF NOT EXISTS shortener (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  task_name TEXT NOT NULL,
  task_massage TEXT NOT NULL DEFAULT '',
  time_task_start DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
  time_task_stop DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
 )
